### ISSUE TITLE
[QnA] Gaps

### ISSUE THREAD

**Issue by justjjasper** [Nugget-Reactor/FEC#64]
https://github.com/Nugget-Reactor/FEC/blob/0e5934a3bb49fa218f840e9b56deafb12b011081/client/src/Components/QnA/QnA.jsx#L1-L8

Just be mindful of the gaps you have within your import section.

**Comment by cwang1014** [comment]
Got it, was using gaps to separate library imports from component imports but will keep in mind this is not best practice.
