### ISSUE TITLE
[QnA] Question/Answer Modal Close Button Positioning

### ISSUE THREAD

**Issue by justjjasper** [Nugget-Reactor/FEC#66]
Adjusting the X(close button) to the top right corner within the Question/Answer is easier for the user experience. At the moment its at the top right corner of users screen(edge of the right screen).

**Comment by cwang1014** [comment]
This wasn't as easy of a fix as I thought but I ended up getting the close button at top right of the form itself instead of at the top right of the screen.

**Comment by justjjasper** [comment]
> This wasn't as easy of a fix as I thought but I ended up getting the close button at top right of the form itself instead of at the top right of the screen.

Indeed, CSS can be tricky :-)
