### ISSUE TITLE
[QnA] Rendering 2 Questions at a time Part 2

### ISSUE THREAD

**Issue by justjjasper** [Nugget-Reactor/FEC#68]
https://github.com/Nugget-Reactor/FEC/blob/0e5934a3bb49fa218f840e9b56deafb12b011081/client/src/Components/QnA/QuestionsList.jsx#L22-L42

After the first code optimization, you're also going to have add another condition to how your "More Answered Questions" button would render.

On Line 37, you would need a third condition where the button would only render if the ```totalCount``` is greater than 2.

**Comment by cwang1014** [comment]
I tried adding the condition you mentioned to only render the button if the totalCount is greater than 2, but it appears that condition was not actually needed as I am still able to have the button disappear with only the condition checking if currCount < totalCount. Thank you Jasper!

**Comment by justjjasper** [comment]
> I tried adding the condition you mentioned to only render the button if the totalCount is greater than 2, but it appears that condition was not actually needed as I am still able to have the button disappear with only the condition checking if currCount < totalCount. Thank you Jasper!

Ahh I see, thanks for implementing the condition and checking for yourself :-).
