### ISSUE TITLE
[RelatedItems] Filtering Optimization

### ISSUE THREAD

**Issue by justjjasper** [Nugget-Reactor/FEC#69]
https://github.com/Nugget-Reactor/FEC/blob/0e5934a3bb49fa218f840e9b56deafb12b011081/client/src/Components/RelatedItems/RelatedItems.jsx#L21-L43

Line 30 through Line 35 is used to filter out a product ID. You're able to refactor this by using the Javascript's Filter method that returns an array based on the condition, instead of handling the filter through a for loop.

An example of a filtering method would be 
```let array = [1, 2, 3, 4, 5]```

```let oddNumbersArray = array.filter(num => num % 2 !== 0)```

This would return an array of odd numbers

Hopefully this is a good example of the filtering method! :)

**Comment by tessathornberry** [comment]
Great, thank you! I implemented this fix and the code is much cleaner and more professional-looking now.
