### ISSUE TITLE
[RelatedItems] Code Flow

### ISSUE THREAD

**Issue by justjjasper** [Nugget-Reactor/FEC#70]
https://github.com/Nugget-Reactor/FEC/blob/65c5b0c865eb3999de047ec9bd08d8dceb32a737/client/src/Components/RelatedItems/OutfitsCarousel.jsx#L38-L69

- Love your code flow where you create a function with that handles the conditional rendering, and then you insert that custom function into the Returns, makes Return section code look more clean. (As seen on Lin38-45, and then returned on Line 62)

**Comment by tessathornberry** [comment]
Thank you so much! I definitely credit my great Hack Reactor teachers and peers for hinting that I COULD organize like this, and also I credit my previous experiences with document processing to understand organizing the steps of a workflow. Keeping things clear and flowing is good for myself coming back to my code, and also for future programmers.
